In [ ]:
import pandas as pd
data=pd.read_csv('/content/pii_dataset.csv (1).zip')
data.head()

,document,text,tokens,trailing_whitespace,labels,prompt,prompt_id,name,email,phone,job,address,username,url,hobby,len
0,1073d46f-2241-459b-ab01-851be8d26436,"My name is Aaliyah Popova, and I am a jeweler ...","['My', 'name', 'is', 'Aaliyah', 'Popova,', 'an...","[True, True, True, True, True, True, True, Tru...","['O', 'O', 'O', 'B-NAME_STUDENT', 'I-NAME_STUD...",\n Aaliyah Popova is a jeweler with 13 year...,1,Aaliyah Popova,aaliyah.popova4783@aol.edu,(95) 94215-7906,jeweler,97 Lincoln Street,NaN,NaN,Podcasting,363
1,5ec717a9-17ee-48cd-9d76-30ae256c9354,"My name is Konstantin Becker, and I'm a develo...","['My', 'name', 'is', 'Konstantin', 'Becker,', ...","[True, True, True, True, True, True, True, Tru...","['O', 'O', 'O', 'B-NAME_STUDENT', 'I-NAME_STUD...",\n Konstantin Becker is a developer with 2 ...,1,Konstantin Becker,konstantin.becker@gmail.com,0475 4429797,developer,826 Webster Street,NaN,NaN,Quilting,255
2,353da41e-7799-4071-ab20-d959b362612e,"As Mieko Mitsubishi, an account manager at a p...","['As', 'Mieko', 'Mitsubishi,', 'an', 'account'...","[True, True, True, True, True, True, True, Tru...","['O', 'B-NAME_STUDENT', 'I-NAME_STUDENT', 'O',...",\n Mieko Mitsubishi is a account manager. W...,3,Mieko Mitsubishi,mieko_mitsubishi@msn.org,+27 61 222 4762,account manager,1309 Southwest 71st Terrace,NaN,NaN,Metal detecting,259
3,9324ee01-7bdc-41b1-a7a5-01307f72c20d,"My name is Kazuo Sun, and I'm an air traffic c...","['My', 'name', 'is', 'Kazuo', 'Sun,', 'and', ""...","[True, True, True, True, True, True, True, Tru...","['O', 'O', 'O', 'B-NAME_STUDENT', 'I-NAME_STUD...",\n Kazuo Sun is a air traffic controller wi...,1,Kazuo Sun,kazuosun@hotmail.net,0304 2215930,air traffic controller,736 Sicard Street Southeast,NaN,NaN,Amateur radio,281
4,971fe266-2739-4f1b-979b-7f64e07d5a4a,"My name is Arina Sun, and I'm a dental hygieni...","['My', 'name', 'is', 'Arina', 'Sun,', 'and', ""...","[True, True, True, True, True, True, True, Tru...","['O', 'O', 'O', 'B-NAME_STUDENT', 'I-NAME_STUD...",\n Arina Sun is a dental hygienist. Write a...,3,Arina Sun,arina-sun@gmail.net,0412 1245924,dental hygienist,5701 North 67th Avenue,NaN,NaN,Related,210

In [ ]:
#let's analyse the data
print(data.shape)
print(data.columns)
print(data.info())

(4434, 16)
Index(['document', 'text', 'tokens', 'trailing_whitespace', 'labels', 'prompt',
       'prompt_id', 'name', 'email', 'phone', 'job', 'address', 'username',
       'url', 'hobby', 'len'],
      dtype='object')
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4434 entries, 0 to 4433
Data columns (total 16 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   document             4434 non-null   object
 1   text                 4434 non-null   object
 2   tokens               4434 non-null   object
 3   trailing_whitespace  4434 non-null   object
 4   labels               4434 non-null   object
 5   prompt               4434 non-null   object
 6   prompt_id            4434 non-null   int64
 7   name                 4434 non-null   object
 8   email                4434 non-null   object
 9   phone                4434 non-null   object
 10  job                  4434 non-null   object
 11  address              4434 non-null   object
 12  username             1322 non-null   object
 13  url                  1322 non-null   object
 14  hobby                4434 non-null   object
 15  len                  4434 non-null   int64
dtypes: int64(2), object(14)
memory usage: 554.4+ KB
None

In [ ]:
# well this things are taking too much time so just leave this part
#all_labels = [label for labels_list in data['labels'] for label in labels_list]
#print(all_labels)
#print(len(all_labels))

In [ ]:
#let's see some information
# qucik look at the data mf
print(data.info())

# let's do some inspection  about the first row
sample = data.iloc[0]  # 1st row
print("Text:", sample['text'][:100]) #printing the firsst 100 words of text
print("Tokens smaple :", sample['tokens'][:5])
print("Labels sample:", sample['labels'][:5])
print("True Name:", sample['name'])

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4434 entries, 0 to 4433
Data columns (total 16 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   document             4434 non-null   object
 1   text                 4434 non-null   object
 2   tokens               4434 non-null   object
 3   trailing_whitespace  4434 non-null   object
 4   labels               4434 non-null   object
 5   prompt               4434 non-null   object
 6   prompt_id            4434 non-null   int64
 7   name                 4434 non-null   object
 8   email                4434 non-null   object
 9   phone                4434 non-null   object
 10  job                  4434 non-null   object
 11  address              4434 non-null   object
 12  username             1322 non-null   object
 13  url                  1322 non-null   object
 14  hobby                4434 non-null   object
 15  len                  4434 non-null   int64
dtypes: int64(2), object(14)
memory usage: 554.4+ KB
None
Text: My name is Aaliyah Popova, and I am a jeweler with 13 years of experience. I remember a very unique
Tokens smaple : ['My'
Labels sample: ['O',
True Name: Aaliyah Popova

In [ ]:
# in this dataset ,there are some values that we can safely drop off
# becuase thay  are of very little use
#occupying unnceceary data ,and can't think of their use at this time
data=data.drop(columns=['prompt','prompt_id','hobby','document','len'])
print(data.columns)

Index(['text', 'tokens', 'trailing_whitespace', 'labels', 'name', 'email',
       'phone', 'job', 'address', 'username', 'url'],
      dtype='object')

In [ ]:
# there  is  one more problem in our dataset ,tokens  and lables are given in string format
# which can be mishandled leading to uncertaininty
import ast



# there was some error fixed-ai help
def safe_parse(val):
    if isinstance(val, list):
        return val
    try:
        # standard JSON double-quote fix
        return json.loads(val.replace("'", '"'))
    except:
        try:
            return eval(val)
        except:
            return []

data['tokens']=data['tokens'].apply(ast.literal_eval)
data['labels']=data['labels'].apply(ast.literal_eval)
# now both are converted into list ,which is quite gooooood



# let's calculate the unique labels that can be formed
unique_labels=sorted(
    list(
        set(
          j for i in data['labels'] for  j in i
        )
    )
)
print(unique_labels)
print(len(unique_labels))

['B-EMAIL', 'B-NAME_STUDENT', 'B-PHONE_NUM', 'B-STREET_ADDRESS', 'B-URL_PERSONAL', 'B-USERNAME', 'I-NAME_STUDENT', 'I-PHONE_NUM', 'I-STREET_ADDRESS', 'O']
10

In [ ]:
# since now we have unique labels ,now we have to map them
# mapping  should be mandatory here bcz ,our model cannot understand text

label_id={label: i  for i,label ,in enumerate(unique_labels) }
id_label={i:label for  i,label,in enumerate(unique_labels)}
# mapping is succwesully done
print(label_id)
print(id_label)

{'B-EMAIL': 0, 'B-NAME_STUDENT': 1, 'B-PHONE_NUM': 2, 'B-STREET_ADDRESS': 3, 'B-URL_PERSONAL': 4, 'B-USERNAME': 5, 'I-NAME_STUDENT': 6, 'I-PHONE_NUM': 7, 'I-STREET_ADDRESS': 8, 'O': 9}
{0: 'B-EMAIL', 1: 'B-NAME_STUDENT', 2: 'B-PHONE_NUM', 3: 'B-STREET_ADDRESS', 4: 'B-URL_PERSONAL', 5: 'B-USERNAME', 6: 'I-NAME_STUDENT', 7: 'I-PHONE_NUM', 8: 'I-STREET_ADDRESS', 9: 'O'}

In [ ]:
# now we will split the data
from sklearn.model_selection import train_test_split

train_data,test_data=train_test_split(data,test_size=0.2,random_state=42)

# this is perfect
print(train_data.shape)
print(test_data.shape)
print(data.shape)

(3547, 11)
(887, 11)
(4434, 11)

In [ ]:
!pip install transformers datasets seqeval -q
# intitally  without tokensier there was a one to one mapping of data labels-word
# but after introduincg toeknsier ,dfor example-bert ,it can split words ,leading to miscalcuation
# for example the situan becomes 10 labels and 15 words;for example



from transformers import AutoTokenizer
MODEL_NAME = "distilbert-base-uncased"
tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)
def tokenize_and_align_labels(examples):
    tokenized_inputs = tokenizer(
        examples["tokens"],
        truncation=True,
        is_split_into_words=True,
        max_length=512
    )

    labels = []
    for i, label in enumerate(examples["labels"]):
        word_ids = tokenized_inputs.word_ids(batch_index=i)
        previous_word_idx = None
        label_ids = []
        for word_idx in word_ids:
            if word_idx is None:
                label_ids.append(-100)  # Special tokens like [CLS], [SEP]
            elif word_idx != previous_word_idx:
                label_ids.append(label_id[label[word_idx]])  # First subword gets real label ID
            else:
                label_ids.append(-100)  # Subsequent subwords ignored in loss calculation
            previous_word_idx = word_idx
        labels.append(label_ids)

    tokenized_inputs["labels"] = labels
    return tokenized_inputs

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.6/43.6 kB 4.5 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Building wheel for seqeval (setup.py) ... done

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

config.json:   0%|          | 0.00/483 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

In [ ]:
# now  finally let's train and test data
from datasets import Dataset
# 1st we will convert pandas dataframes to hugging face dataset
train_h_f = Dataset.from_pandas(train_data)
test_h_f = Dataset.from_pandas(test_data)
# map tokenisation and alignment
train_tokenized=train_h_f.map(tokenize_and_align_labels,batched=True)
test_tokenized=test_h_f.map(tokenize_and_align_labels,batched=True)

Map:   0%|          | 0/3547 [00:00<?, ? examples/s]

Map:   0%|          | 0/887 [00:00<?, ? examples/s]

In [ ]:
# let's also do some inspection

# this will print column name in general
print("keys created:", train_tokenized[0].keys())
# this will print tokens
print("token sample:",train_tokenized[0]['tokens'][:10])
# this will print the assigned value to
print("label sample:",train_tokenized[0]['labels'][:10])

keys created: dict_keys(['text', 'tokens', 'trailing_whitespace', 'labels', 'name', 'email', 'phone', 'job', 'address', 'username', 'url', '__index_level_0__', 'input_ids', 'token_type_ids', 'attention_mask'])
token sample: ["I'm", 'Tatiana', 'Yamada,', 'a', 'mechanic', 'with', 'two', 'years', 'of', 'experience']
label sample: [-100, 9, -100, -100, 1, 6, -100, -100, 9, 9]

In [ ]:
# now we should load a pretrained model that has been already pretrained on billions oof data
#  obviosuly we cannot implimnet everything from scratch

In [ ]:
from transformers import AutoModelForTokenClassification, TrainingArguments, Trainer, DataCollatorForTokenClassification

# 1. Initialize pretrained model with your label mappings
model = AutoModelForTokenClassification.from_pretrained(
    "distilbert-base-uncased",
    num_labels=len(label_id),
    id2label=id_label,
    label2id=label_id
)

# 2. Dynamic padding collator
data_collator = DataCollatorForTokenClassification(tokenizer=tokenizer)

# 3. Training arguments
training_args = TrainingArguments(
    output_dir="./results",
    eval_strategy="epoch",
    learning_rate=2e-5,
    per_device_train_batch_size=16,
    per_device_eval_batch_size=16,
    num_train_epochs=3,
    weight_decay=0.01,
    logging_steps=50,
    save_strategy="epoch"
)

# 4. Initialize Trainer (removed 'tokenizer' argument)
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_tokenized,
    eval_dataset=test_tokenized,
    data_collator=data_collator,
)

# 5. Start training
trainer.train()

model.safetensors: reconstructing file:   0%|          |  0.00B /  268MB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/100 [00:00<?, ?it/s]

[transformers] DistilBertForTokenClassification LOAD REPORT from: distilbert-base-uncased
Key                     | Status     |
------------------------+------------+-
vocab_layer_norm.weight | UNEXPECTED |
vocab_projector.bias    | UNEXPECTED |
vocab_transform.bias    | UNEXPECTED |
vocab_transform.weight  | UNEXPECTED |
vocab_layer_norm.bias   | UNEXPECTED |
classifier.weight       | MISSING    |
classifier.bias         | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
/usr/local/lib/python3.12/dist-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)

In [ ]:
import numpy as np
from seqeval.metrics import classification_report, f1_score

# Get predictions on validation set
predictions, labels, _ = trainer.predict(test_tokenized)
preds = np.argmax(predictions, axis=2)

# Filter out -100 (ignored tokens)
true_predictions = [
    [id_label[p] for (p, l) in zip(prediction, label) if l != -100]
    for prediction, label in zip(preds, labels)
]
true_labels = [
    [id_label[l] for (p, l) in zip(prediction, label) if l != -100]
    for prediction, label in zip(preds, labels)
]

print(classification_report(true_labels, true_predictions))

                precision    recall  f1-score   support

         EMAIL       0.91      1.00      0.95       733
  NAME_STUDENT       0.98      0.98      0.98      2066
     PHONE_NUM       0.97      0.96      0.97       474
STREET_ADDRESS       0.98      0.95      0.96       692
  URL_PERSONAL       0.95      0.95      0.95       129
      USERNAME       0.94      0.81      0.87       143

     micro avg       0.96      0.97      0.97      4237
     macro avg       0.96      0.94      0.95      4237
  weighted avg       0.96      0.97      0.97      4237

In [ ]:
import torch

def redact_pii(text):
    tokens = text.split()

    # 1. Tokenize pre-split words (returns a BatchEncoding object)
    inputs = tokenizer(tokens, is_split_into_words=True, return_tensors="pt", truncation=True, max_length=512)

    # 2. Extract word_ids BEFORE converting inputs to a dict
    word_ids = inputs.word_ids()

    # 3. Move tensors to GPU/device
    inputs = {k: v.to(model.device) for k, v in inputs.items()}

    with torch.no_grad():
        outputs = model(**inputs)

    predictions = torch.argmax(outputs.logits, dim=2)[0].cpu().numpy()

    redacted_tokens = []
    last_word_idx = None

    for idx, word_idx in enumerate(word_ids):
        # Skip [CLS], [SEP], or repeated subwords of the same token
        if word_idx is None or word_idx == last_word_idx:
            continue

        pred_label = id_label[predictions[idx]]

        if pred_label != 'O':
            redacted_tokens.append("[REDACTED]")
        else:
            redacted_tokens.append(tokens[word_idx])

        last_word_idx = word_idx

    return " ".join(redacted_tokens)

# Test on a sample string
sample_text = "Hello, my name is Sarah Conner and my email is sarah@example.com."
print("Original:", sample_text)
print("Redacted:", redact_pii(sample_text))

Original: Hello, my name is Sarah Conner and my email is sarah@example.com.
Redacted: Hello, my name is [REDACTED] [REDACTED] and my email is sarah@example.com.

In [ ]:
# let's just save it

# Save model and tokenizer to disk
model.save_pretrained("./pii_detector_model")
tokenizer.save_pretrained("./pii_detector_model")

print("Model and tokenizer saved successfully!")

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Model and tokenizer saved successfully!